### ISSUE TITLE
Google Drive download indefinite file size & Direct video stream playback 'seek' issue (related)

### ISSUE THREAD

**Issue by pctechkid** [patheticGeek/torrent-aio-bot#31]
I tried copying the link of video files from the drive tab and played it directly without downloading first through VLC Media Player. Fortunately, the videos played fine.
```js
Note: I changed the URL encoding of google drive links in my fork as VLC wont accept '[' and ']' characters and as a result will have playback error, I replaced it with %5B for '[' and %5D for ']'
```
Now the issue is, you can't seek the playback time. My thoughts of this is that because the file size given by google drive is INDEFINITE as you can notice when you download a file in the drive tab.

So, is it possible for any fix for this? If only the file size is fixed when trying to download from drive, the playback seek would be resolved also.

This is very helpful for users who prefer to stream directly the media files via external players rather than downloading it.

**Comment by patheticGeek** [comment]
The url of file that important, you can change the file name at the end and put whatever in it, the name is just there so that file downloads with that name the only important part is the ?id= at the end thats the file id. So i think i should fix this just by using the slugify module. And yes gdrive drive provides size and other things i just need to add intermidiation of headers between the bot and gdrive requests.

Last thing it is not indefined its undefined

**Comment by patheticGeek** [comment]
This issues if fixed please update your fork.
